
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-TypoFix","number":42,"title":"Fixed typo in footer","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/42"},{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"KateUnger-general-search","number":41,"title":"Add General Search to Dropdown","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/41"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-CreateCourseDropdownMenu","number":40,"title":"Added Course Dropdown Menu for Personal Schedules","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/40"},{"author":{"id":"MDQ6VXNlcjMyMzgwMzU3","is_bot":false,"login":"KateUnger","name":"Kate Unger"},"headRefName":"KateUnger-add-col","number":38,"title":"Add Button Column","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/38"},{"author":{"id":"MDQ6VXNlcjY3OTIyMzg2","is_bot":false,"login":"adyahrastogi","name":""},"headRefName":"adyahrastogi-coursedetails","number":35,"title":"Placeholders for CourseDetailsPage","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/35"},{"author":{"id":"U_kgDOCLmKQA","is_bot":false,"login":"rosillo-m","name":"Mariana Rosillo"},"headRefName":"Mariana-AddInfoToTable","number":34,"title":"Priority: Added additional information/columns to CourseDetailsTable","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/34"}]
