
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-CourseDetailsPageStories","number":46,"title":"Modify .stories files for CourseDetailsPage and CourseDetailsTable","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/46"},{"author":{"id":"U_kgDOBim1JQ","is_bot":false,"login":"ivan512az","name":"Ivan Hernandez"},"headRefName":"Ivan-CourseDetailsPage","number":45,"title":"Populated Course Details Page","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/45"}]
