
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-3
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2NzAzNDk0","is_bot":false,"login":"mucucsb","name":""},"headRefName":"Mu-PersonalSchedule","number":30,"title":"BUG: Creating personal schedule fails first try until quarter field changed","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/30"},{"author":{"id":"MDQ6VXNlcjIyMzU4NDcx","is_bot":false,"login":"ThatsBadJuju","name":""},"headRefName":"Kevin-FirstSectionLectureBug","number":29,"title":"Bugfix: Searching for a TA makes the first section appear as a lecture","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-3/pull/29"}]
